mkdir -p assets/seed_images/destinations assets/seed_images/activities assets/icons assets/illustrations docs/screenshots firebase/emulator functions/src/optimiser functions/src/types lib/core/config lib/core/firebase lib/core/theme lib/core/constants lib/core/ui lib/core/utils lib/features/auth/data lib/features/auth/domain lib/features/auth/presentation lib/features/trips/data lib/features/trips/domain lib/features/trips/presentation lib/features/itinerary/data lib/features/itinerary/domain lib/features/itinerary/presentation lib/features/checklist/data lib/features/checklist/domain lib/features/checklist/presentation lib/features/discovery/presentation lib/features/profile/data lib/features/profile/presentation test/unit test/widget test/integration

touch lib/core/config/app_config.dart lib/core/config/router_config.dart lib/core/firebase/firebase_providers.dart lib/core/theme/app_theme.dart lib/core/theme/app_colors.dart lib/core/theme/app_text_styles.dart lib/core/constants/spacing.dart lib/core/constants/durations.dart lib/core/constants/strings.dart lib/core/ui/app_button.dart lib/core/ui/app_card.dart lib/core/ui/app_text_field.dart lib/core/ui/empty_state.dart lib/core/ui/error_state.dart lib/core/ui/loading_state.dart lib/core/utils/logger.dart lib/core/utils/extensions.dart

touch lib/features/auth/data/auth_repository.dart lib/features/auth/data/auth_repository_provider.dart lib/features/auth/domain/app_user.dart lib/features/auth/presentation/sign_in_screen.dart lib/features/auth/presentation/sign_up_screen.dart lib/features/auth/presentation/forgot_password_screen.dart lib/features/auth/presentation/auth_notifier.dart lib/features/trips/data/trip_repository.dart lib/features/trips/data/trip_dto.dart lib/features/trips/domain/trip.dart lib/features/trips/presentation/trip_dashboard_screen.dart lib/features/trips/presentation/create_trip_screen.dart lib/features/trips/presentation/trips_notifier.dart lib/features/itinerary/data/activity_repository.dart lib/features/itinerary/data/activity_dto.dart lib/features/itinerary/domain/activity.dart lib/features/itinerary/presentation/itinerary_builder_screen.dart lib/features/itinerary/presentation/activity_card.dart lib/features/itinerary/presentation/add_edit_activity_screen.dart lib/features/itinerary/presentation/itinerary_notifier.dart lib/features/checklist/data/checklist_repository.dart lib/features/checklist/data/checklist_item_dto.dart lib/features/checklist/domain/checklist_item.dart lib/features/checklist/presentation/checklist_screen.dart lib/features/checklist/presentation/checklist_notifier.dart lib/features/discovery/presentation/activity_discovery_screen.dart lib/features/profile/data/user_repository.dart lib/features/profile/presentation/profile_screen.dart lib/features/profile/presentation/profile_notifier.dart

touch test/unit/.gitkeep test/widget/.gitkeep test/integration/.gitkeep

touch firebase/firestore.rules firebase/firestore.indexes.json firebase/storage.rules firebase/emulator/seed.js firebase.json .firebaserc functions/src/index.ts functions/src/optimiser/optimiser.ts functions/src/optimiser/optimiser.test.ts functions/src/types/models.ts functions/tsconfig.json

echo "Done. Files created:"
find lib -type f | sort
